import type { INodeProperties } from 'n8n-workflow';

export const appointmentCrewOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['appointmentCrew'] } },
		options: [
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete an appointment crew entry',
				description: 'Delete an appointment crew entry by ID',
				routing: { request: { method: 'DELETE' } },
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get an appointment crew entry',
				description: 'Get a single appointment crew entry by ID',
				routing: {
					request: { method: 'GET' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many appointment crew entries',
				description: 'Get a list of appointment crew entries',
				routing: {
					request: { method: 'GET', url: '/appointmentcrew' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update an appointment crew entry',
				description: 'Update an existing appointment crew entry',
				routing: {
					request: { method: 'PUT' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
		],
		default: 'getAll',
	},
];

export const appointmentCrewFields: INodeProperties[] = [
	{
		displayName: 'Appointment Crew ID',
		name: 'appointmentCrewId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['appointmentCrew'], operation: ['get', 'update', 'delete'] } },
		default: '',
		description: 'The ID of the appointment crew entry',
		routing: { request: { url: '=/appointmentcrew/{{$value}}' } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: { show: { resource: ['appointmentCrew'], operation: ['getAll'] } },
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		routing: {
			send: { paginate: '={{ $value }}' },
			operations: {
				pagination: {
					type: 'generic',
					properties: {
						continue: '={{ !!$response.body?.next_page_url }}',
						request: { url: '={{ $response.body?.next_page_url ?? $request.url }}' },
					},
				},
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: { show: { resource: ['appointmentCrew'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		routing: { request: { qs: { limit: '={{ $value }}' } } },
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		displayOptions: { show: { resource: ['appointmentCrew'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 0 },
		default: 0,
		description: 'Number of results to skip for offset-based pagination',
		routing: { request: { qs: { offset: '={{ $value > 0 ? $value : undefined }}' } } },
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		displayOptions: { show: { resource: ['appointmentCrew'], operation: ['getAll'] } },
		default: {},
		options: [
			{
			displayName: 'Appointment (Path)',
			name: 'appointment',
			type: 'string',
			default: '',
			placeholder: '/appointments/42',
			description: 'Filter by appointment resource path',
			routing: { request: { qs: { appointment: '={{ $value }}' } } },
			},
			{
			displayName: 'Created After',
			name: 'created_gt',
			type: 'dateTime',
			default: '',
			description: 'Return only records created after this date',
			routing: { request: { qs: { 'created[gt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Fields',
			name: 'fields',
			type: 'string',
			default: '',
			placeholder: 'ID,displayname,modified',
			description: 'Comma-separated list of fields to return. Leave empty for all fields.',
			routing: { request: { qs: { fields: '={{ $value || undefined }}' } } },
			},
			{
			displayName: 'ID Greater Than',
			name: 'id_gt',
			type: 'number',
			default: 0,
			description: 'Return only records with ID greater than this value (useful for incremental sync)',
			routing: { request: { qs: { 'id[gt]': '={{ $value > 0 ? $value : undefined }}' } } },
			},
			{
			displayName: 'Modified After',
			name: 'modified_gt',
			type: 'dateTime',
			default: '',
			description: 'Return only records modified after this date',
			routing: { request: { qs: { 'modified[gt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Modified Before',
			name: 'modified_lt',
			type: 'dateTime',
			default: '',
			description: 'Return only records modified before this date',
			routing: { request: { qs: { 'modified[lt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Sort',
			name: 'sort',
			type: 'string',
			default: '+id',
			placeholder: '+ID or -modified',
			description: 'Sort field with direction prefix: + for ascending, - for descending',
			routing: { request: { qs: { sort: '={{ $value }}' } } },
			},
		],
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { resource: ['appointmentCrew'], operation: ['update'] } },
		default: {},
		options: [
			{
				displayName: 'Remark',
				name: 'remark',
				type: 'string',
				typeOptions: { rows: 3 },
				default: '',
				routing: { request: { body: { remark: '={{ $value }}' } } },
			},
		],
	},
];
