import type { INodeProperties } from 'n8n-workflow';
import { customQueryParamsField, rentmanPagination } from './shared';

export const costOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['cost'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a cost',
				description: 'Create a cost item in a project (POST /projects/{ID}/costs)',
				routing: {
					request: { method: 'POST' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a cost',
				description: 'Delete a cost by ID',
				routing: {
					request: { method: 'DELETE' },
					output: {
						postReceive: [
							{
								type: 'set',
								properties: {
									value: '={{ { "deleted": true } }}',
								},
							},
						],
					},
				},
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a cost',
				description: 'Get a single cost by ID',
				routing: {
					request: { method: 'GET' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many costs',
				description: 'Get a list of costs',
				routing: {
					request: { method: 'GET', url: '/costs' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a cost',
				description: 'Update an existing cost',
				routing: {
					request: { method: 'PUT' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
		],
		default: 'getAll',
	},
];

const costBodyFields: INodeProperties['options'] = [
	{
		displayName: 'Custom Fields',
		name: 'custom',
		type: 'json',
		default: '{}',
		description: 'Custom fields as JSON object, e.g. {"custom_1": "text", "custom_2": 5}. The field names are listed under Extra Input Field.',
		routing: { request: { body: { custom: "={{ typeof $value === 'string' ? JSON.parse($value || '{}') : $value }}" } } },
	},
	{
		displayName: 'Discount',
		name: 'discount',
		type: 'number',
		default: 0,
		routing: { request: { body: { discount: '={{ $value }}' } } },
	},
	{
		displayName: 'Ledger (Path)',
		name: 'ledger',
		type: 'string',
		default: '',
		placeholder: '/ledgercodes/0',
		routing: { request: { body: { ledger: '={{ $value }}' } } },
	},
	{
		displayName: 'Ledger Debit (Path)',
		name: 'ledger_debit',
		type: 'string',
		default: '',
		placeholder: '/ledgercodes/0',
		description: 'Resource path of a debit ledger code (one with is_debit); Rentman rejects credit ledger codes here',
		routing: { request: { body: { ledger_debit: '={{ $value }}' } } },
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		routing: { request: { body: { name: '={{ $value }}' } } },
	},
	{
		displayName: 'Purchase Price',
		name: 'purchase_price',
		type: 'number',
		default: 0,
		routing: { request: { body: { purchase_price: '={{ $value }}' } } },
	},
	{
		displayName: 'Quantity',
		name: 'quantity',
		type: 'number',
		default: 0,
		routing: { request: { body: { quantity: '={{ $value }}' } } },
	},
	{
		displayName: 'Remark',
		name: 'remark',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		routing: { request: { body: { remark: '={{ $value }}' } } },
	},
	{
		displayName: 'Sale Price',
		name: 'sale_price',
		type: 'number',
		default: 0,
		routing: { request: { body: { sale_price: '={{ $value }}' } } },
	},
	{
		displayName: 'Tax Class (Path)',
		name: 'taxclass',
		type: 'string',
		default: '',
		placeholder: '/taxclasses/0',
		description: 'This class, in combination with the chosen VAT scheme at project level, determines the final VAT rate',
		routing: { request: { body: { taxclass: '={{ $value }}' } } },
	},
	{
		displayName: 'Template',
		name: 'is_template',
		type: 'boolean',
		default: false,
		routing: { request: { body: { is_template: '={{ $value }}' } } },
	},
];

export const costFields: INodeProperties[] = [
	{
		displayName: 'Project ID',
		name: 'projectId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['cost'], operation: ['create'] } },
		default: '',
		description: 'The ID of the project to add the cost to',
		routing: { request: { url: '=/projects/{{$value}}/costs' } },
	},
	{
		displayName: 'Cost ID',
		name: 'costId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['cost'], operation: ['get', 'update', 'delete'] } },
		default: '',
		description: 'The ID of the cost',
		routing: { request: { url: '=/costs/{{$value}}' } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: { show: { resource: ['cost'], operation: ['getAll'] } },
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		routing: {
			send: { paginate: true },
			operations: {
				pagination: rentmanPagination,
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: { show: { resource: ['cost'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		routing: { request: { qs: { limit: '={{ $value }}' } } },
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		displayOptions: { show: { resource: ['cost'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 0 },
		default: 0,
		description: 'Number of results to skip for offset-based pagination',
		routing: { request: { qs: { offset: '={{ $value > 0 ? $value : undefined }}' } } },
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		displayOptions: { show: { resource: ['cost'], operation: ['getAll'] } },
		default: {},
		options: [
			{
			displayName: 'Created After',
			name: 'created_gt',
			type: 'dateTime',
			default: '',
			description: 'Return only records created after this date',
			routing: { request: { qs: { 'created[gt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Fields',
			name: 'fields',
			type: 'string',
			default: '',
			placeholder: 'ID,displayname,modified',
			description: 'Comma-separated list of fields to return. Custom fields can be requested as custom_N; together with Expand, dot notation limits an expanded record (e.g. equipment.name). Leave empty for all fields.',
			routing: { request: { qs: { fields: '={{ $value || undefined }}' } } },
			},
			{
			displayName: 'ID Greater Than',
			name: 'id_gt',
			type: 'number',
			default: 0,
			description: 'Return only records with ID greater than this value (useful for incremental sync)',
			routing: { request: { qs: { 'id[gt]': '={{ $value > 0 ? $value : undefined }}' } } },
			},
			{
			displayName: 'Modified After',
			name: 'modified_gt',
			type: 'dateTime',
			default: '',
			description: 'Return only records modified after this date',
			routing: { request: { qs: { 'modified[gt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Modified Before',
			name: 'modified_lt',
			type: 'dateTime',
			default: '',
			description: 'Return only records modified before this date',
			routing: { request: { qs: { 'modified[lt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Sort',
			name: 'sort',
			type: 'string',
			default: '+id',
			placeholder: '+ID or -modified',
			description: 'Sort field with direction prefix: + for ascending, - for descending',
			routing: { request: { qs: { sort: '={{ $value }}' } } },
			},
		],
	},
	{
		displayName: 'Subproject (Path)',
		name: 'subproject',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['cost'], operation: ['create', 'update'] } },
		default: '',
		placeholder: '/subprojects/155',
		description: 'Resource path of the subproject the cost belongs to (required by the API on create and update)',
		routing: { request: { body: { subproject: '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { resource: ['cost'], operation: ['create'] } },
		default: {},
		options: costBodyFields,
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { resource: ['cost'], operation: ['update'] } },
		default: {},
		options: costBodyFields,
	},
	customQueryParamsField('cost'),
];
