import type { INodeProperties } from 'n8n-workflow';

export const crewAvailabilityOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['crewAvailability'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a crew availability entry',
				description: 'Create a new crew availability entry',
				routing: {
					request: { method: 'POST', url: '/crewavailability' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a crew availability entry',
				description: 'Delete a crew availability entry by ID',
				routing: {
					request: { method: 'DELETE' },
					output: {
						postReceive: [
							{
								type: 'set',
								properties: {
									value: '={{ { "deleted": true } }}',
								},
							},
						],
					},
				},
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a crew availability entry',
				description: 'Get a single crew availability entry by ID',
				routing: {
					request: { method: 'GET' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Get Collection',
				value: 'getAll',
				action: 'Get collection of crew availability entries',
				description: 'Get a list of crew availability entries',
				routing: {
					request: { method: 'GET', url: '/crewavailability' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a crew availability entry',
				description: 'Update an existing crew availability entry',
				routing: {
					request: { method: 'PUT' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
		],
		default: 'getAll',
	},
];

export const crewAvailabilityFields: INodeProperties[] = [
	{
		displayName: 'Crew Availability ID',
		name: 'crewAvailabilityId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['crewAvailability'], operation: ['get', 'update', 'delete'] } },
		default: '',
		description: 'The ID of the crew availability entry',
		routing: { request: { url: '=/crewavailability/{{$value}}' } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: { show: { resource: ['crewAvailability'], operation: ['getAll'] } },
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		routing: {
			send: { paginate: true },
			operations: {
				pagination: {
					type: 'generic',
					properties: {
						continue: '={{ !!$response.body?.next_page_url && $parameter["returnAll"] }}',
						request: { url: '={{ $response.body?.next_page_url ?? $request.url }}' },
					},
				},
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: { show: { resource: ['crewAvailability'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		routing: { request: { qs: { limit: '={{ $value }}' } } },
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		displayOptions: { show: { resource: ['crewAvailability'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 0 },
		default: 0,
		description: 'Number of results to skip for offset-based pagination',
		routing: { request: { qs: { offset: '={{ $value > 0 ? $value : undefined }}' } } },
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		displayOptions: { show: { resource: ['crewAvailability'], operation: ['getAll'] } },
		default: {},
		options: [
			{
			displayName: 'Created After',
			name: 'created_gt',
			type: 'dateTime',
			default: '',
			description: 'Return only records created after this date',
			routing: { request: { qs: { 'created[gt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Crew Member (Path)',
			name: 'crewmember',
			type: 'string',
			default: '',
			placeholder: '/crew/42',
			description: 'Filter by crew member resource path',
			routing: { request: { qs: { crewmember: '={{ $value }}' } } },
			},
			{
			displayName: 'Fields',
			name: 'fields',
			type: 'string',
			default: '',
			placeholder: 'ID,displayname,modified',
			description: 'Comma-separated list of fields to return. Leave empty for all fields.',
			routing: { request: { qs: { fields: '={{ $value || undefined }}' } } },
			},
			{
			displayName: 'ID Greater Than',
			name: 'id_gt',
			type: 'number',
			default: 0,
			description: 'Return only records with ID greater than this value (useful for incremental sync)',
			routing: { request: { qs: { 'id[gt]': '={{ $value > 0 ? $value : undefined }}' } } },
			},
			{
			displayName: 'Modified After',
			name: 'modified_gt',
			type: 'dateTime',
			default: '',
			description: 'Return only records modified after this date',
			routing: { request: { qs: { 'modified[gt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Modified Before',
			name: 'modified_lt',
			type: 'dateTime',
			default: '',
			description: 'Return only records modified before this date',
			routing: { request: { qs: { 'modified[lt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Sort',
			name: 'sort',
			type: 'string',
			default: '+id',
			placeholder: '+ID or -modified',
			description: 'Sort field with direction prefix: + for ascending, - for descending',
			routing: { request: { qs: { sort: '={{ $value }}' } } },
			},
		],
	},
	// ─── CREATE ──────────────────────────────────────────────────────────────
	{
		displayName: 'Crew Member (Path)',
		name: 'crewmember',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['crewAvailability'], operation: ['create'] } },
		default: '',
		placeholder: '/crew/42',
		description: 'Resource path of the crew member, e.g. /crew/42',
		routing: { request: { body: { crewmember: '={{ $value }}' } } },
	},
	{
		displayName: 'Start Date/Time',
		name: 'start',
		type: 'dateTime',
		required: true,
		displayOptions: { show: { resource: ['crewAvailability'], operation: ['create'] } },
		default: '',
		description: 'Start of the availability period',
		routing: { request: { body: { start: '={{ $value }}' } } },
	},
	{
		displayName: 'End Date/Time',
		name: 'end',
		type: 'dateTime',
		required: true,
		displayOptions: { show: { resource: ['crewAvailability'], operation: ['create'] } },
		default: '',
		description: 'End of the availability period',
		routing: { request: { body: { end: '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { resource: ['crewAvailability'], operation: ['create'] } },
		default: {},
		options: [
			{
				displayName: 'Remark',
				name: 'remark',
				type: 'string',
				typeOptions: { rows: 3 },
				default: '',
				routing: { request: { body: { remark: '={{ $value }}' } } },
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{ name: 'Not Available', value: 'N' },
					{ name: 'Available', value: 'Y' },
				],
				default: 'N',
				description: 'Availability status of the crew member',
				routing: { request: { body: { status: '={{ $value }}' } } },
			},
		],
	},
	// ─── UPDATE ──────────────────────────────────────────────────────────────
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { resource: ['crewAvailability'], operation: ['update'] } },
		default: {},
		options: [
			{
				displayName: 'End Date/Time',
				name: 'end',
				type: 'dateTime',
				default: '',
				routing: { request: { body: { end: '={{ $value }}' } } },
			},
			{
				displayName: 'Remark',
				name: 'remark',
				type: 'string',
				typeOptions: { rows: 3 },
				default: '',
				routing: { request: { body: { remark: '={{ $value }}' } } },
			},
			{
				displayName: 'Start Date/Time',
				name: 'start',
				type: 'dateTime',
				default: '',
				routing: { request: { body: { start: '={{ $value }}' } } },
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{ name: 'Not Available', value: 'N' },
					{ name: 'Available', value: 'Y' },
				],
				default: 'N',
				description: 'Availability status of the crew member',
				routing: { request: { body: { status: '={{ $value }}' } } },
			},
		],
	},
];
