import type { INodeProperties } from 'n8n-workflow';
import { customQueryParamsField } from './shared';

// ─── LEAVE MUTATION ───────────────────────────────────────────────────────────

export const leaveMutationOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['leaveMutation'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a leave mutation',
				description: 'Create a new leave balance mutation',
				routing: {
					request: { method: 'POST', url: '/leavemutation' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a leave mutation',
				description: 'Get a single leave mutation by ID',
				routing: {
					request: { method: 'GET' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Get Collection',
				value: 'getAll',
				action: 'Get collection of leave mutations',
				description: 'Get a list of leave mutations',
				routing: {
					request: { method: 'GET', url: '/leavemutation' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
		],
		default: 'getAll',
	},
];

export const leaveMutationFields: INodeProperties[] = [
	{
		displayName: 'Leave Mutation ID',
		name: 'leaveMutationId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['leaveMutation'], operation: ['get'] } },
		default: '',
		description: 'The ID of the leave mutation',
		routing: { request: { url: '=/leavemutation/{{$value}}' } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: { show: { resource: ['leaveMutation'], operation: ['getAll'] } },
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		routing: {
			send: { paginate: true },
			operations: {
				pagination: {
					type: 'generic',
					properties: {
						continue: '={{ !!$response.body?.next_page_url && $parameter["returnAll"] }}',
						request: { url: '={{ $response.body?.next_page_url ?? $request.url }}' },
					},
				},
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: { show: { resource: ['leaveMutation'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		routing: { request: { qs: { limit: '={{ $value }}' } } },
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		displayOptions: { show: { resource: ['leaveMutation'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 0 },
		default: 0,
		description: 'Number of results to skip for offset-based pagination',
		routing: { request: { qs: { offset: '={{ $value > 0 ? $value : undefined }}' } } },
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		displayOptions: { show: { resource: ['leaveMutation'], operation: ['getAll'] } },
		default: {},
		options: [
			{
			displayName: 'Created After',
			name: 'created_gt',
			type: 'dateTime',
			default: '',
			description: 'Return only records created after this date',
			routing: { request: { qs: { 'created[gt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Crew Member (Path)',
			name: 'crewmember',
			type: 'string',
			default: '',
			placeholder: '/crew/42',
			description: 'Filter by crew member resource path',
			routing: { request: { qs: { crewmember: '={{ $value }}' } } },
			},
			{
			displayName: 'Fields',
			name: 'fields',
			type: 'string',
			default: '',
			placeholder: 'ID,displayname,modified',
			description: 'Comma-separated list of fields to return. Leave empty for all fields.',
			routing: { request: { qs: { fields: '={{ $value || undefined }}' } } },
			},
			{
			displayName: 'ID Greater Than',
			name: 'id_gt',
			type: 'number',
			default: 0,
			description: 'Return only records with ID greater than this value (useful for incremental sync)',
			routing: { request: { qs: { 'id[gt]': '={{ $value > 0 ? $value : undefined }}' } } },
			},
			{
			displayName: 'Modified After',
			name: 'modified_gt',
			type: 'dateTime',
			default: '',
			description: 'Return only records modified after this date',
			routing: { request: { qs: { 'modified[gt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Modified Before',
			name: 'modified_lt',
			type: 'dateTime',
			default: '',
			description: 'Return only records modified before this date',
			routing: { request: { qs: { 'modified[lt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Sort',
			name: 'sort',
			type: 'string',
			default: '-created',
			placeholder: '+ID or -created',
			description: 'Sort field with direction prefix: + for ascending, - for descending',
			routing: { request: { qs: { sort: '={{ $value }}' } } },
			},
		],
	},
	{
		displayName: 'Crew Member (Path)',
		name: 'crewmember',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['leaveMutation'], operation: ['create'] } },
		default: '',
		placeholder: '/crew/42',
		description: 'Resource path of the crew member, e.g. /crew/42',
		routing: { request: { body: { crewmember: '={{ $value }}' } } },
	},
	{
		displayName: 'Leave Type (Path)',
		name: 'leavetype',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['leaveMutation'], operation: ['create'] } },
		default: '',
		placeholder: '/leavetypes/1',
		description: 'Resource path of the leave type, e.g. /leavetypes/1',
		routing: { request: { body: { leavetype: '={{ $value }}' } } },
	},
	{
		displayName: 'Duration (Seconds)',
		name: 'duration',
		type: 'number',
		required: true,
		displayOptions: { show: { resource: ['leaveMutation'], operation: ['create'] } },
		default: 0,
		description: 'Duration in seconds to add (positive) or subtract (negative) from the leave balance',
		routing: { request: { body: { duration: '={{ $value }}' } } },
	},
	{
		displayName: 'Mutation Date',
		name: 'mutation_date',
		type: 'dateTime',
		required: true,
		displayOptions: { show: { resource: ['leaveMutation'], operation: ['create'] } },
		default: '',
		description: 'The date for this leave balance mutation',
		routing: { request: { body: { mutation_date: '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { resource: ['leaveMutation'], operation: ['create'] } },
		default: {},
		options: [
			{
				displayName: 'Remark',
				name: 'remark',
				type: 'string',
				typeOptions: { rows: 3 },
				default: '',
				routing: { request: { body: { remark: '={{ $value }}' } } },
			},
		],
	},
];

// ─── LEAVE REQUEST ────────────────────────────────────────────────────────────

export const leaveRequestOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['leaveRequest'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a leave request',
				description: 'Create a new leave request',
				routing: {
					request: { method: 'POST', url: '/leaverequest' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a leave request',
				description: 'Get a single leave request by ID',
				routing: {
					request: { method: 'GET' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Get Collection',
				value: 'getAll',
				action: 'Get collection of leave requests',
				description: 'Get a list of leave requests',
				routing: {
					request: { method: 'GET', url: '/leaverequest' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a leave request',
				description: 'Update an existing leave request',
				routing: {
					request: { method: 'PUT' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
		],
		default: 'getAll',
	},
];

export const leaveRequestFields: INodeProperties[] = [
	{
		displayName: 'Leave Request ID',
		name: 'leaveRequestId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['leaveRequest'], operation: ['get', 'update'] } },
		default: '',
		description: 'The ID of the leave request',
		routing: { request: { url: '=/leaverequest/{{$value}}' } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: { show: { resource: ['leaveRequest'], operation: ['getAll'] } },
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		routing: {
			send: { paginate: true },
			operations: {
				pagination: {
					type: 'generic',
					properties: {
						continue: '={{ !!$response.body?.next_page_url && $parameter["returnAll"] }}',
						request: { url: '={{ $response.body?.next_page_url ?? $request.url }}' },
					},
				},
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: { show: { resource: ['leaveRequest'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		routing: { request: { qs: { limit: '={{ $value }}' } } },
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		displayOptions: { show: { resource: ['leaveRequest'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 0 },
		default: 0,
		description: 'Number of results to skip for offset-based pagination',
		routing: { request: { qs: { offset: '={{ $value > 0 ? $value : undefined }}' } } },
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		displayOptions: { show: { resource: ['leaveRequest'], operation: ['getAll'] } },
		default: {},
		options: [
			{
			displayName: 'Approval Status',
			name: 'approval_status',
			type: 'options',
			options: [
			{ name: 'Pending', value: 'pending' },
			{ name: 'Approved', value: 'approved' },
			{ name: 'Rejected', value: 'rejected' },
			],
			default: 'pending',
			description: 'Filter by approval status',
			routing: { request: { qs: { approval_status: '={{ $value }}' } } },
			},
			{
			displayName: 'Created After',
			name: 'created_gt',
			type: 'dateTime',
			default: '',
			description: 'Return only records created after this date',
			routing: { request: { qs: { 'created[gt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Fields',
			name: 'fields',
			type: 'string',
			default: '',
			placeholder: 'ID,displayname,modified',
			description: 'Comma-separated list of fields to return. Leave empty for all fields.',
			routing: { request: { qs: { fields: '={{ $value || undefined }}' } } },
			},
			{
			displayName: 'ID Greater Than',
			name: 'id_gt',
			type: 'number',
			default: 0,
			description: 'Return only records with ID greater than this value (useful for incremental sync)',
			routing: { request: { qs: { 'id[gt]': '={{ $value > 0 ? $value : undefined }}' } } },
			},
			{
			displayName: 'Modified After',
			name: 'modified_gt',
			type: 'dateTime',
			default: '',
			description: 'Return only records modified after this date',
			routing: { request: { qs: { 'modified[gt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Modified Before',
			name: 'modified_lt',
			type: 'dateTime',
			default: '',
			description: 'Return only records modified before this date',
			routing: { request: { qs: { 'modified[lt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Requested For (Path)',
			name: 'requested_for',
			type: 'string',
			default: '',
			placeholder: '/crew/42',
			description: 'Filter by crew member resource path',
			routing: { request: { qs: { requested_for: '={{ $value }}' } } },
			},
			{
			displayName: 'Sort',
			name: 'sort',
			type: 'string',
			default: '-created',
			placeholder: '+ID or -created',
			description: 'Sort field with direction prefix: + for ascending, - for descending',
			routing: { request: { qs: { sort: '={{ $value }}' } } },
			},
		],
	},
	{
		displayName: 'Requested For (Path)',
		name: 'requested_for',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['leaveRequest'], operation: ['create'] } },
		default: '',
		placeholder: '/crew/42',
		description: 'Resource path of the crew member this request is for, e.g. /crew/42',
		routing: { request: { body: { requested_for: '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { resource: ['leaveRequest'], operation: ['create'] } },
		default: {},
		options: [
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				typeOptions: { rows: 3 },
				default: '',
				routing: { request: { body: { description: '={{ $value }}' } } },
			},
		],
	},
	{
		displayName: 'Requested For (Path)',
		name: 'requested_for',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['leaveRequest'], operation: ['update'] } },
		default: '',
		placeholder: '/crew/42',
		description: 'Resource path of the crew member (required by the API for updates)',
		routing: { request: { body: { requested_for: '={{ $value }}' } } },
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { resource: ['leaveRequest'], operation: ['update'] } },
		default: {},
		options: [
			{
				displayName: 'Approval Status',
				name: 'approval_status',
				type: 'options',
				options: [
					{ name: 'Pending', value: 'pending' },
					{ name: 'Approved', value: 'approved' },
					{ name: 'Rejected', value: 'rejected' },
				],
				default: 'pending',
				description: 'Approval status of the leave request',
				routing: { request: { body: { approval_status: '={{ $value }}' } } },
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				typeOptions: { rows: 3 },
				default: '',
				routing: { request: { body: { description: '={{ $value }}' } } },
			},
		],
	},
	customQueryParamsField('leaveMutation'),
	customQueryParamsField('leaveRequest'),
];
