import type { INodeProperties } from 'n8n-workflow';
import { customQueryParamsField, rentmanPagination } from './shared';

export const paymentOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['payment'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a payment',
				description: 'Register a payment on an invoice (POST /invoices/{ID}/payments)',
				routing: {
					request: { method: 'POST' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a payment',
				description: 'Get a single payment by ID',
				routing: {
					request: { method: 'GET' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Get Collection',
				value: 'getAll',
				action: 'Get collection of payments',
				description: 'Get a list of payments',
				routing: {
					request: { method: 'GET', url: '/payments' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a payment',
				description: 'Update an existing payment',
				routing: {
					request: { method: 'PUT' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
		],
		default: 'getAll',
	},
];

const paymentBodyFields: INodeProperties[] = [
	{
		displayName: 'Amount',
		name: 'amount',
		type: 'number',
		default: 0,
		routing: { request: { body: { amount: '={{ $value }}' } } },
	},
	{
		displayName: 'Description',
		name: 'remark',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		routing: { request: { body: { description: '={{ $value }}' } } },
	},
	{
		displayName: 'Import Source',
		name: 'payment_import_source',
		type: 'options',
		options: [
			{ name: 'Exact Online', value: 'exactonline' },
			{ name: 'None', value: 'none' },
			{ name: 'Public API', value: 'publicapi' },
			{ name: 'QuickBooks', value: 'quickbooks' },
			{ name: 'Xero', value: 'xero' },
		],
		default: 'publicapi',
		routing: { request: { body: { payment_import_source: '={{ $value }}' } } },
	},
	];

export const paymentFields: INodeProperties[] = [
	{
		displayName: 'Invoice ID',
		name: 'invoiceId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['payment'], operation: ['create'] } },
		default: '',
		description: 'The ID of the invoice the payment belongs to',
		routing: { request: { url: '=/invoices/{{$value}}/payments' } },
	},
	{
		displayName: 'Payment ID',
		name: 'paymentId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['payment'], operation: ['get', 'update'] } },
		default: '',
		description: 'The ID of the payment',
		routing: { request: { url: '=/payments/{{$value}}' } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: { show: { resource: ['payment'], operation: ['getAll'] } },
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		routing: {
			send: { paginate: true },
			operations: {
				pagination: rentmanPagination,
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: { show: { resource: ['payment'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		routing: { request: { qs: { limit: '={{ $value }}' } } },
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		displayOptions: { show: { resource: ['payment'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 0 },
		default: 0,
		description: 'Number of results to skip for offset-based pagination',
		routing: { request: { qs: { offset: '={{ $value > 0 ? $value : undefined }}' } } },
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		displayOptions: { show: { resource: ['payment'], operation: ['getAll'] } },
		default: {},
		options: [
			{
			displayName: 'Created After',
			name: 'created_gt',
			type: 'dateTime',
			default: '',
			description: 'Return only records created after this date',
			routing: { request: { qs: { 'created[gt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Fields',
			name: 'fields',
			type: 'string',
			default: '',
			placeholder: 'ID,displayname,modified',
			description: 'Comma-separated list of fields to return. Custom fields can be requested as custom_N. Leave empty for all fields.',
			routing: { request: { qs: { fields: '={{ $value || undefined }}' } } },
			},
			{
			displayName: 'ID Greater Than',
			name: 'id_gt',
			type: 'number',
			default: 0,
			description: 'Return only records with ID greater than this value (useful for incremental sync)',
			routing: { request: { qs: { 'id[gt]': '={{ $value > 0 ? $value : undefined }}' } } },
			},
			{
			displayName: 'Modified After',
			name: 'modified_gt',
			type: 'dateTime',
			default: '',
			description: 'Return only records modified after this date',
			routing: { request: { qs: { 'modified[gt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Modified Before',
			name: 'modified_lt',
			type: 'dateTime',
			default: '',
			description: 'Return only records modified before this date',
			routing: { request: { qs: { 'modified[lt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Sort',
			name: 'sort',
			type: 'string',
			default: '-created',
			placeholder: '+ID or -created',
			description: 'Sort field with direction prefix: + for ascending, - for descending',
			routing: { request: { qs: { sort: '={{ $value }}' } } },
			},
		],
	},
	{
		displayName: 'Payment Date',
		name: 'moment',
		type: 'dateTime',
		required: true,
		displayOptions: { show: { resource: ['payment'], operation: ['create'] } },
		default: '',
		description: 'When the payment was made',
		routing: { request: { body: { moment: '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { resource: ['payment'], operation: ['create'] } },
		default: {},
		options: paymentBodyFields,
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { resource: ['payment'], operation: ['update'] } },
		default: {},
		options: [
			{
				displayName: 'Payment Date',
				// Named "date" as in 26.5.0, so saved workflows keep their value; Rentman's field is "moment".
				name: 'date',
				type: 'dateTime',
				default: '',
				description: 'When the payment was made. Rentman requires it on every update.',
				routing: { request: { body: { moment: '={{ $value }}' } } },
			},
			...paymentBodyFields,
		],
	},
	customQueryParamsField('payment'),
];
