import type { INodeProperties } from 'n8n-workflow';
import { customQueryParamsField, rentmanPagination, sortByDisplayName } from './shared';

// ─── PROJECT REQUESTS ─────────────────────────────────────────────────────────

export const projectRequestOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['projectRequest'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a project request',
				description: 'Create a new project request',
				routing: {
					request: { method: 'POST', url: '/projectrequests' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a project request',
				description: 'Delete a project request by ID',
				routing: {
					request: { method: 'DELETE' },
					output: {
						postReceive: [
							{
								type: 'set',
								properties: {
									value: '={{ { "deleted": true } }}',
								},
							},
						],
					},
				},
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a project request',
				description: 'Get a single project request by ID',
				routing: {
					request: { method: 'GET' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Get Collection',
				value: 'getAll',
				action: 'Get collection of project requests',
				description: 'Get a list of project requests',
				routing: {
					request: { method: 'GET', url: '/projectrequests' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a project request',
				description: 'Update an existing project request',
				routing: {
					request: { method: 'PUT' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
		],
		default: 'getAll',
	},
];

const projectRequestBodyFields: INodeProperties[] = [
	{
		displayName: 'Contact City',
		name: 'contact_mailing_city',
		type: 'string',
		default: '',
		routing: { request: { body: { contact_mailing_city: '={{ $value }}' } } },
	},
	{
		displayName: 'Contact Country',
		name: 'contact_mailing_country',
		type: 'string',
		default: '',
		routing: { request: { body: { contact_mailing_country: '={{ $value }}' } } },
	},
	{
		displayName: 'Contact House Number',
		name: 'contact_mailing_number',
		type: 'string',
		default: '',
		routing: { request: { body: { contact_mailing_number: '={{ $value }}' } } },
	},
	{
		displayName: 'Contact Name',
		name: 'contact_name',
		type: 'string',
		default: '',
		routing: { request: { body: { contact_name: '={{ $value }}' } } },
	},
	{
		displayName: 'Contact Person Email',
		name: 'contact_person_email',
		type: 'string',
		default: '',
		routing: { request: { body: { contact_person_email: '={{ $value }}' } } },
	},
	{
		displayName: 'Contact Person First Name',
		name: 'contact_person_first_name',
		type: 'string',
		default: '',
		routing: { request: { body: { contact_person_first_name: '={{ $value }}' } } },
	},
	{
		displayName: 'Contact Person Last Name',
		name: 'contact_person_lastname',
		type: 'string',
		default: '',
		routing: { request: { body: { contact_person_lastname: '={{ $value }}' } } },
	},
	{
		displayName: 'Contact Person Middle Name',
		name: 'contact_person_middle_name',
		type: 'string',
		default: '',
		routing: { request: { body: { contact_person_middle_name: '={{ $value }}' } } },
	},
	{
		displayName: 'Contact Phone',
		name: 'contact_phone',
		type: 'string',
		default: '',
		routing: { request: { body: { contact_phone: '={{ $value }}' } } },
	},
	{
		displayName: 'Contact Postal Code',
		name: 'contact_mailing_postalcode',
		type: 'string',
		default: '',
		routing: { request: { body: { contact_mailing_postalcode: '={{ $value }}' } } },
	},
	{
		displayName: 'Contact Street',
		name: 'contact_mailing_street',
		type: 'string',
		default: '',
		routing: { request: { body: { contact_mailing_street: '={{ $value }}' } } },
	},
	{
		displayName: 'Delivery (Out)',
		name: 'out',
		type: 'dateTime',
		default: '',
		routing: { request: { body: { out: '={{ $value }}' } } },
	},
	{
		displayName: 'External Reference',
		name: 'external_reference',
		type: 'number',
		default: 0,
		routing: { request: { body: { external_reference: '={{ $value }}' } } },
	},
	{
		displayName: 'Language',
		name: 'language',
		type: 'string',
		default: '',
		routing: { request: { body: { language: '={{ $value }}' } } },
	},
	{
		displayName: 'Linked Contact (Path)',
		name: 'customer',
		type: 'string',
		default: '',
		placeholder: '/contacts/42',
		description: 'Resource path of the contact this request belongs to, e.g. /contacts/42',
		routing: { request: { body: { linked_contact: '={{ $value }}' } } },
	},
	{
		displayName: 'Location City',
		name: 'location_mailing_city',
		type: 'string',
		default: '',
		routing: { request: { body: { location_mailing_city: '={{ $value }}' } } },
	},
	{
		displayName: 'Location Country',
		name: 'location_mailing_country',
		type: 'string',
		default: '',
		routing: { request: { body: { location_mailing_country: '={{ $value }}' } } },
	},
	{
		displayName: 'Location House Number',
		name: 'location_mailing_number',
		type: 'string',
		default: '',
		routing: { request: { body: { location_mailing_number: '={{ $value }}' } } },
	},
	{
		displayName: 'Location Name',
		name: 'location_name',
		type: 'string',
		default: '',
		routing: { request: { body: { location_name: '={{ $value }}' } } },
	},
	{
		displayName: 'Location Phone',
		name: 'location_phone',
		type: 'string',
		default: '',
		routing: { request: { body: { location_phone: '={{ $value }}' } } },
	},
	{
		displayName: 'Location Postal Code',
		name: 'location_mailing_postalcode',
		type: 'string',
		default: '',
		routing: { request: { body: { location_mailing_postalcode: '={{ $value }}' } } },
	},
	{
		displayName: 'Location Street',
		name: 'location_mailing_street',
		type: 'string',
		default: '',
		routing: { request: { body: { location_mailing_street: '={{ $value }}' } } },
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		routing: { request: { body: { name: '={{ $value }}' } } },
	},
	{
		displayName: 'Paid',
		name: 'is_paid',
		type: 'boolean',
		default: false,
		routing: { request: { body: { is_paid: '={{ $value }}' } } },
	},
	{
		displayName: 'Price',
		name: 'price',
		type: 'number',
		default: 0,
		routing: { request: { body: { price: '={{ $value }}' } } },
	},
	{
		displayName: 'Remark',
		name: 'remark',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		routing: { request: { body: { remark: '={{ $value }}' } } },
	},
	{
		displayName: 'Return (In)',
		name: 'in',
		type: 'dateTime',
		default: '',
		routing: { request: { body: { in: '={{ $value }}' } } },
	},
	{
		displayName: 'Usage Period End',
		name: 'usageperiod_end',
		type: 'dateTime',
		default: '',
		routing: { request: { body: { usageperiod_end: '={{ $value }}' } } },
	},
	{
		displayName: 'Usage Period Start',
		name: 'usageperiod_start',
		type: 'dateTime',
		default: '',
		routing: { request: { body: { usageperiod_start: '={{ $value }}' } } },
	},
];

export const projectRequestFields: INodeProperties[] = [
	{
		displayName: 'Project Request ID',
		name: 'projectRequestId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['projectRequest'], operation: ['get', 'update', 'delete'] } },
		default: '',
		description: 'The ID of the project request',
		routing: { request: { url: '=/projectrequests/{{$value}}' } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: { show: { resource: ['projectRequest'], operation: ['getAll'] } },
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		routing: {
			send: { paginate: true },
			operations: {
				pagination: rentmanPagination,
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: { show: { resource: ['projectRequest'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		routing: { request: { qs: { limit: '={{ $value }}' } } },
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		displayOptions: { show: { resource: ['projectRequest'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 0 },
		default: 0,
		description: 'Number of results to skip for offset-based pagination',
		routing: { request: { qs: { offset: '={{ $value > 0 ? $value : undefined }}' } } },
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		displayOptions: { show: { resource: ['projectRequest'], operation: ['getAll'] } },
		default: {},
		options: [
			{
			displayName: 'Created After',
			name: 'created_gt',
			type: 'dateTime',
			default: '',
			description: 'Return only records created after this date',
			routing: { request: { qs: { 'created[gt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Fields',
			name: 'fields',
			type: 'string',
			default: '',
			placeholder: 'ID,displayname,modified',
			description: 'Comma-separated list of fields to return. Custom fields can be requested as custom_N; together with Expand, dot notation limits an expanded record (e.g. equipment.name). Leave empty for all fields.',
			routing: { request: { qs: { fields: '={{ $value || undefined }}' } } },
			},
			{
			displayName: 'ID Greater Than',
			name: 'id_gt',
			type: 'number',
			default: 0,
			description: 'Return only records with ID greater than this value (useful for incremental sync)',
			routing: { request: { qs: { 'id[gt]': '={{ $value > 0 ? $value : undefined }}' } } },
			},
			{
			displayName: 'Modified After',
			name: 'modified_gt',
			type: 'dateTime',
			default: '',
			description: 'Return only records modified after this date',
			routing: { request: { qs: { 'modified[gt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Modified Before',
			name: 'modified_lt',
			type: 'dateTime',
			default: '',
			description: 'Return only records modified before this date',
			routing: { request: { qs: { 'modified[lt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Sort',
			name: 'sort',
			type: 'string',
			default: '+id',
			placeholder: '+ID or -modified',
			description: 'Sort field with direction prefix: + for ascending, - for descending',
			routing: { request: { qs: { sort: '={{ $value }}' } } },
			},
		],
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['projectRequest'], operation: ['create'] } },
		default: '',
		description: 'Name of the project request',
		routing: { request: { body: { name: '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { resource: ['projectRequest'], operation: ['create'] } },
		default: {},
		options: sortByDisplayName([
			{
				displayName: 'Plan Period End',
				name: 'planperiod_end',
				type: 'dateTime',
				default: '',
				description: 'End of the planning period. Rentman requires start and end on create.',
				routing: { request: { body: { planperiod_end: '={{ $value }}' } } },
			},
			{
				displayName: 'Plan Period Start',
				name: 'planperiod_start',
				type: 'dateTime',
				default: '',
				description: 'Start of the planning period. Rentman requires start and end on create.',
				routing: { request: { body: { planperiod_start: '={{ $value }}' } } },
			},
			...projectRequestBodyFields.filter((field) => field.name !== 'name'),
		]),
	},
	{
		displayName: 'Plan Period Start',
		name: 'planperiod_start',
		type: 'dateTime',
		required: true,
		displayOptions: { show: { resource: ['projectRequest'], operation: ['update'] } },
		default: '',
		description: 'Start of the planning period (required by the API)',
		routing: { request: { body: { planperiod_start: '={{ $value }}' } } },
	},
	{
		displayName: 'Plan Period End',
		name: 'planperiod_end',
		type: 'dateTime',
		required: true,
		displayOptions: { show: { resource: ['projectRequest'], operation: ['update'] } },
		default: '',
		description: 'End of the planning period (required by the API)',
		routing: { request: { body: { planperiod_end: '={{ $value }}' } } },
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { resource: ['projectRequest'], operation: ['update'] } },
		default: {},
		options: projectRequestBodyFields,
	},
];

// ─── PROJECT REQUEST EQUIPMENT ────────────────────────────────────────────────

export const projectRequestEquipmentOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['projectRequestEquipment'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a project request equipment entry',
				description: 'Add an equipment line to a project request (POST /projectrequests/{ID}/projectrequestequipment)',
				routing: {
					request: { method: 'POST' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a project request equipment entry',
				description: 'Delete a project request equipment entry by ID',
				routing: {
					request: { method: 'DELETE' },
					output: {
						postReceive: [
							{
								type: 'set',
								properties: {
									value: '={{ { "deleted": true } }}',
								},
							},
						],
					},
				},
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a project request equipment entry',
				description: 'Get a single project request equipment entry by ID',
				routing: {
					request: { method: 'GET' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Get Collection',
				value: 'getAll',
				action: 'Get collection of project request equipment entries',
				description: 'Get a list of project request equipment entries',
				routing: {
					request: { method: 'GET', url: '/projectrequestequipment' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a project request equipment entry',
				description: 'Update an existing project request equipment entry',
				routing: {
					request: { method: 'PUT' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'data' } }] },
				},
			},
		],
		default: 'getAll',
	},
];

const projectRequestEquipmentBodyFields: INodeProperties['options'] = [
	{
		displayName: 'Comment',
		name: 'is_comment',
		type: 'boolean',
		default: false,
		routing: { request: { body: { is_comment: '={{ $value }}' } } },
	},
	{
		displayName: 'Discount',
		name: 'discount',
		type: 'number',
		default: 0,
		routing: { request: { body: { discount: '={{ $value }}' } } },
	},
	{
		displayName: 'External Remark',
		name: 'remark',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		routing: { request: { body: { external_remark: '={{ $value }}' } } },
	},
	{
		displayName: 'Factor',
		name: 'factor',
		type: 'string',
		default: '',
		routing: { request: { body: { factor: '={{ $value }}' } } },
	},
	{
		displayName: 'Kit',
		name: 'is_kit',
		type: 'boolean',
		default: false,
		routing: { request: { body: { is_kit: '={{ $value }}' } } },
	},
	{
		displayName: 'Linked Equipment (Path)',
		name: 'linked_equipment',
		type: 'string',
		default: '',
		placeholder: '/equipment/0',
		routing: { request: { body: { linked_equipment: '={{ $value }}' } } },
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		routing: { request: { body: { name: '={{ $value }}' } } },
	},
	{
		displayName: 'Order',
		name: 'order',
		type: 'string',
		default: '',
		routing: { request: { body: { order: '={{ $value }}' } } },
	},
	{
		displayName: 'Parent (Path)',
		name: 'parent',
		type: 'string',
		default: '',
		placeholder: '/projectrequestequipment/0',
		description: 'The combination it is part of',
		routing: { request: { body: { parent: '={{ $value }}' } } },
	},
	{
		displayName: 'Quantity',
		name: 'quantity',
		type: 'number',
		default: 1,
		routing: { request: { body: { quantity: '={{ $value }}' } } },
	},
	{
		displayName: 'Quantity Total',
		name: 'quantity_total',
		type: 'number',
		default: 0,
		routing: { request: { body: { quantity_total: '={{ $value }}' } } },
	},
	{
		displayName: 'Unit Price',
		name: 'unit_price',
		type: 'number',
		default: 0,
		routing: { request: { body: { unit_price: '={{ $value }}' } } },
	},
];

export const projectRequestEquipmentFields: INodeProperties[] = [
	{
		displayName: 'Project Request ID',
		name: 'projectRequestId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['projectRequestEquipment'], operation: ['create'] } },
		default: '',
		description: 'The ID of the project request to add the equipment line to',
		routing: { request: { url: '=/projectrequests/{{$value}}/projectrequestequipment' } },
	},
	{
		displayName: 'Project Request Equipment ID',
		name: 'projectRequestEquipmentId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['projectRequestEquipment'], operation: ['get', 'update', 'delete'] } },
		default: '',
		description: 'The ID of the project request equipment entry',
		routing: { request: { url: '=/projectrequestequipment/{{$value}}' } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: { show: { resource: ['projectRequestEquipment'], operation: ['getAll'] } },
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		routing: {
			send: { paginate: true },
			operations: {
				pagination: rentmanPagination,
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: { show: { resource: ['projectRequestEquipment'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		routing: { request: { qs: { limit: '={{ $value }}' } } },
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		displayOptions: { show: { resource: ['projectRequestEquipment'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 0 },
		default: 0,
		description: 'Number of results to skip for offset-based pagination',
		routing: { request: { qs: { offset: '={{ $value > 0 ? $value : undefined }}' } } },
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		displayOptions: { show: { resource: ['projectRequestEquipment'], operation: ['getAll'] } },
		default: {},
		options: [
			{
			displayName: 'Created After',
			name: 'created_gt',
			type: 'dateTime',
			default: '',
			description: 'Return only records created after this date',
			routing: { request: { qs: { 'created[gt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Fields',
			name: 'fields',
			type: 'string',
			default: '',
			placeholder: 'ID,displayname,modified',
			description: 'Comma-separated list of fields to return. Custom fields can be requested as custom_N; together with Expand, dot notation limits an expanded record (e.g. equipment.name). Leave empty for all fields.',
			routing: { request: { qs: { fields: '={{ $value || undefined }}' } } },
			},
			{
			displayName: 'ID Greater Than',
			name: 'id_gt',
			type: 'number',
			default: 0,
			description: 'Return only records with ID greater than this value (useful for incremental sync)',
			routing: { request: { qs: { 'id[gt]': '={{ $value > 0 ? $value : undefined }}' } } },
			},
			{
			displayName: 'Modified After',
			name: 'modified_gt',
			type: 'dateTime',
			default: '',
			description: 'Return only records modified after this date',
			routing: { request: { qs: { 'modified[gt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Modified Before',
			name: 'modified_lt',
			type: 'dateTime',
			default: '',
			description: 'Return only records modified before this date',
			routing: { request: { qs: { 'modified[lt]': '={{ $value }}' } } },
			},
			{
			displayName: 'Project Request (Path)',
			name: 'projectrequest',
			type: 'string',
			default: '',
			placeholder: '/projectrequests/42',
			description: 'Filter by project request resource path',
			routing: { request: { qs: { project_request: '={{ $value }}' } } },
			},
			{
			displayName: 'Sort',
			name: 'sort',
			type: 'string',
			default: '+id',
			placeholder: '+ID or -modified',
			description: 'Sort field with direction prefix: + for ascending, - for descending',
			routing: { request: { qs: { sort: '={{ $value }}' } } },
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { resource: ['projectRequestEquipment'], operation: ['create'] } },
		default: {},
		options: projectRequestEquipmentBodyFields,
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { resource: ['projectRequestEquipment'], operation: ['update'] } },
		default: {},
		options: projectRequestEquipmentBodyFields,
	},
	customQueryParamsField('projectRequest'),
	customQueryParamsField('projectRequestEquipment'),
];
