import type { INodeProperties } from 'n8n-workflow';
import { customQueryParamsField } from './shared';

const postReceive = [{ type: 'rootProperty' as const, properties: { property: 'data' } }];

// Parent resource paths supported by /{parent}/{id}/tasks endpoints.
// Used to dynamically build the URL for the linked GET/POST operations.
const taskParentOptions = [
	{ name: 'Contact', value: 'contacts' },
	{ name: 'Contact Person', value: 'contactpersons' },
	{ name: 'Contract', value: 'contracts' },
	{ name: 'Crew', value: 'crew' },
	{ name: 'Equipment', value: 'equipment' },
	{ name: 'Invoice', value: 'invoices' },
	{ name: 'Project', value: 'projects' },
	{ name: 'Purchase Order', value: 'purchaseorders' },
	{ name: 'Quote', value: 'quotes' },
	{ name: 'Repair', value: 'repairs' },
	{ name: 'Serial Number', value: 'serialnumbers' },
	{ name: 'Sub Rental', value: 'subrentals' },
	{ name: 'Supplier', value: 'suppliers' },
	{ name: 'Vehicle', value: 'vehicles' },
];

const taskBodyFields: INodeProperties['options'] = [
	{
		displayName: 'Assignment Type',
		name: 'assignment_type',
		type: 'options',
		options: [
			{ name: 'All Crew Members', value: 'all_crewmembers' },
			{ name: 'Creator Only', value: 'creator_only' },
			{ name: 'Selected Crew Members', value: 'selected_crewmembers' },
		],
		default: 'all_crewmembers',
		routing: { request: { body: { assignment_type: '={{ $value }}' } } },
	},
	{
		displayName: 'Completed At',
		name: 'completed_at',
		type: 'dateTime',
		default: '',
		routing: { request: { body: { completed_at: '={{ $value || null }}' } } },
	},
	{
		displayName: 'Completed By (Path)',
		name: 'completed_by',
		type: 'string',
		default: '',
		placeholder: '/crew/0',
		description: 'Resource path of the crew member who completed the task',
		routing: { request: { body: { completed_by: '={{ $value }}' } } },
	},
	{
		displayName: 'Deadline',
		name: 'deadline',
		type: 'dateTime',
		default: '',
		routing: { request: { body: { deadline: '={{ $value || null }}' } } },
	},
	{
		displayName: 'Deadline Relative Offset Amount',
		name: 'deadline_relative_offset_amount',
		type: 'number',
		default: 0,
		routing: { request: { body: { deadline_relative_offset_amount: '={{ $value }}' } } },
	},
	{
		displayName: 'Deadline Relative Offset Base',
		name: 'deadline_relative_offset_base',
		type: 'options',
		options: [
			{ name: 'End of Period', value: 'end_of_period' },
			{ name: 'Start of Period', value: 'start_of_period' },
		],
		default: 'start_of_period',
		routing: { request: { body: { deadline_relative_offset_base: '={{ $value }}' } } },
	},
	{
		displayName: 'Deadline Relative Offset Direction',
		name: 'deadline_relative_offset_direction',
		type: 'options',
		options: [
			{ name: 'After', value: 'after' },
			{ name: 'Before', value: 'before' },
		],
		default: 'before',
		routing: { request: { body: { deadline_relative_offset_direction: '={{ $value }}' } } },
	},
	{
		displayName: 'Deadline Relative Offset Unit',
		name: 'deadline_relative_offset_unit',
		type: 'options',
		options: [
			{ name: 'Days', value: 'days' },
			{ name: 'Hours', value: 'hours' },
		],
		default: 'days',
		routing: { request: { body: { deadline_relative_offset_unit: '={{ $value }}' } } },
	},
	{
		displayName: 'Deadline Type',
		name: 'deadline_type',
		type: 'options',
		options: [
			{ name: 'Relative to Project Time', value: 'relative_to_project_time' },
			{ name: 'Specific Date', value: 'specific_date' },
		],
		default: 'specific_date',
		routing: { request: { body: { deadline_type: '={{ $value }}' } } },
	},
	{
		displayName: 'Details',
		name: 'details',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		routing: { request: { body: { details: '={{ $value }}' } } },
	},
	{
		displayName: 'Expiry Notification Date',
		name: 'expiry_notification_date',
		type: 'dateTime',
		default: '',
		routing: { request: { body: { expiry_notification_date: '={{ $value || null }}' } } },
	},
	{
		displayName: 'Is Template',
		name: 'is_template',
		type: 'boolean',
		default: false,
		routing: { request: { body: { is_template: '={{ $value }}' } } },
	},
	{
		displayName: 'Item (ID)',
		name: 'item',
		type: 'number',
		default: 0,
		description: 'Numeric ID of the linked item (plain integer, not a path)',
		routing: { request: { body: { item: '={{ $value > 0 ? $value : undefined }}' } } },
	},
	{
		displayName: 'Item Type',
		name: 'itemtype',
		type: 'options',
		options: [
			{ name: 'Contact', value: 'Contact' },
			{ name: 'Contact Person', value: 'ContactPerson' },
			{ name: 'Container', value: 'Container' },
			{ name: 'Contract', value: 'Contract' },
			{ name: 'Crew', value: 'Crew' },
			{ name: 'Equipment', value: 'Equipment' },
			{ name: 'Inspection Report Serial Number', value: 'InspectionReportSerialNumber' },
			{ name: 'Inventory Count Job', value: 'InventoryCountJob' },
			{ name: 'Invoice', value: 'Factuur' },
			{ name: 'Lost Equipment', value: 'LostEquipment' },
			{ name: 'Project', value: 'Project' },
			{ name: 'Purchase Order', value: 'PurchaseOrder' },
			{ name: 'Quote', value: 'Quotation' },
			{ name: 'Repair', value: 'Repair' },
			{ name: 'Serial Number', value: 'SerialNumber' },
			{ name: 'Statistic', value: 'Statistic' },
			{ name: 'Sub Rental', value: 'Subrental' },
			{ name: 'Supplier', value: 'Supplier' },
			{ name: 'Vehicle', value: 'Vehicle' },
		],
		default: 'Project',
		routing: { request: { body: { itemtype: '={{ $value }}' } } },
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		routing: { request: { body: { name: '={{ $value }}' } } },
	},
	{
		displayName: 'Order',
		name: 'order',
		type: 'string',
		default: '',
		routing: { request: { body: { order: '={{ $value }}' } } },
	},
	{
		displayName: 'Priority',
		name: 'priority',
		type: 'options',
		options: [
			{ name: 'High', value: 'high_priority' },
			{ name: 'Low', value: 'low_priority' },
			{ name: 'Medium', value: 'medium_priority' },
			{ name: 'No Priority', value: 'no_priority' },
		],
		default: 'no_priority',
		routing: { request: { body: { priority: '={{ $value }}' } } },
	},
	{
		displayName: 'Public',
		name: 'public',
		type: 'options',
		options: [
			{ name: 'Private', value: 0 },
			{ name: 'Public', value: 1 },
		],
		default: 1,
		routing: { request: { body: { public: '={{ $value }}' } } },
	},
	{
		displayName: 'Recurrence Period',
		name: 'recurperiode',
		type: 'number',
		default: 0,
		description: 'Recurrence period (interval between recurrences)',
		routing: { request: { body: { recurperiode: '={{ $value }}' } } },
	},
	{
		displayName: 'Recurrence Type',
		name: 'recurhoe',
		type: 'options',
		options: [
			{ name: 'Days', value: 'days' },
			{ name: 'Months', value: 'months' },
			{ name: 'Once', value: 'once' },
			{ name: 'Specific Days', value: 'specific_days' },
			{ name: 'Weeks', value: 'weeks' },
			{ name: 'Years', value: 'years' },
		],
		default: 'once',
		routing: { request: { body: { recurhoe: '={{ $value }}' } } },
	},
	{
		displayName: 'Recurrence End',
		name: 'recureind',
		type: 'string',
		default: '',
		description: 'Recurrence end identifier',
		routing: { request: { body: { recureind: '={{ $value }}' } } },
	},
	{
		displayName: 'Status (Path)',
		name: 'status',
		type: 'string',
		default: '',
		placeholder: '/taskstatuses/0',
		description: 'Resource path of the task status',
		routing: { request: { body: { status: '={{ $value }}' } } },
	},
	{
		displayName: 'Synchronization ID',
		name: 'synchronization_id',
		type: 'string',
		default: '',
		routing: { request: { body: { synchronization_id: '={{ $value }}' } } },
	},
	{
		displayName: 'Synchronization URI',
		name: 'synchronization_uri',
		type: 'string',
		default: '',
		routing: { request: { body: { synchronization_uri: '={{ $value }}' } } },
	},
	{
		displayName: 'Time Budget',
		name: 'time_budget',
		type: 'number',
		default: 0,
		routing: { request: { body: { time_budget: '={{ $value }}' } } },
	},
];

export const taskOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['task'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a task',
				description: 'Create a new task',
				routing: {
					request: { method: 'POST', url: '/tasks' },
					output: { postReceive },
				},
			},
			{
				name: 'Create For Parent',
				value: 'createForParent',
				action: 'Create a task linked to a parent resource',
				description: 'Create a task under a parent resource (POST /{parent}/{ID}/tasks)',
				routing: {
					request: { method: 'POST' },
					output: { postReceive },
				},
			},
			{
				name: 'Create Subtask',
				value: 'createSubtask',
				action: 'Create a subtask',
				description: 'Create a subtask under a parent task',
				routing: {
					request: { method: 'POST' },
					output: { postReceive },
				},
			},
			{
				name: 'Create Task Assignment',
				value: 'createTaskAssignment',
				action: 'Create a task assignment',
				description: 'Create a task assignment under a parent task',
				routing: {
					request: { method: 'POST' },
					output: { postReceive },
				},
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a task',
				description: 'Delete a task by ID',
				routing: {
					request: { method: 'DELETE' },
					output: {
						postReceive: [
							{
								type: 'set',
								properties: { value: '={{ { "deleted": true } }}' },
							},
						],
					},
				},
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a task',
				description: 'Get a single task by ID',
				routing: { request: { method: 'GET' }, output: { postReceive } },
			},
			{
				name: 'Get Collection',
				value: 'getAll',
				action: 'Get collection of tasks',
				description: 'Get a list of tasks',
				routing: { request: { method: 'GET', url: '/tasks' }, output: { postReceive } },
			},
			{
				name: 'Get File Folders',
				value: 'getFileFolders',
				action: 'Get task file folders',
				description: 'Get file folders attached to a task',
				routing: { request: { method: 'GET' }, output: { postReceive } },
			},
			{
				name: 'Get Files',
				value: 'getFiles',
				action: 'Get task files',
				description: 'Get files attached to a task',
				routing: { request: { method: 'GET' }, output: { postReceive } },
			},
			{
				name: 'Get For Parent',
				value: 'getForParent',
				action: 'Get tasks for a parent resource',
				description: 'Get tasks linked to a parent resource (GET /{parent}/{ID}/tasks)',
				routing: { request: { method: 'GET' }, output: { postReceive } },
			},
			{
				name: 'Get Subtasks',
				value: 'getSubtasks',
				action: 'Get subtasks',
				description: 'Get all subtasks of a task',
				routing: { request: { method: 'GET' }, output: { postReceive } },
			},
			{
				name: 'Get Task Assignments',
				value: 'getTaskAssignments',
				action: 'Get task assignments',
				description: 'Get all task assignments of a task',
				routing: { request: { method: 'GET' }, output: { postReceive } },
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a task',
				description: 'Update an existing task',
				routing: { request: { method: 'PUT' }, output: { postReceive } },
			},
		],
		default: 'getAll',
	},
];

export const taskFields: INodeProperties[] = [
	// ── Task ID for get/update/delete ────────────────────────────────────────
	{
		displayName: 'Task ID',
		name: 'taskId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['task'], operation: ['get', 'update', 'delete'] } },
		default: '',
		description: 'The ID of the task',
		routing: { request: { url: '=/tasks/{{$value}}' } },
	},
	// ── Task ID for getFiles ─────────────────────────────────────────────────
	{
		displayName: 'Task ID',
		name: 'taskId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['task'], operation: ['getFiles'] } },
		default: '',
		description: 'The ID of the task',
		routing: { request: { url: '=/tasks/{{$value}}/files' } },
	},
	// ── Task ID for getFileFolders ───────────────────────────────────────────
	{
		displayName: 'Task ID',
		name: 'taskId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['task'], operation: ['getFileFolders'] } },
		default: '',
		description: 'The ID of the task',
		routing: { request: { url: '=/tasks/{{$value}}/file_folders' } },
	},
	// ── Task ID for getSubtasks/createSubtask ────────────────────────────────
	{
		displayName: 'Task ID',
		name: 'taskId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['task'], operation: ['getSubtasks', 'createSubtask'] } },
		default: '',
		description: 'The ID of the parent task',
		routing: { request: { url: '=/tasks/{{$value}}/subtasks' } },
	},
	// ── Task ID for getTaskAssignments/createTaskAssignment ──────────────────
	{
		displayName: 'Task ID',
		name: 'taskId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['task'], operation: ['getTaskAssignments', 'createTaskAssignment'] } },
		default: '',
		description: 'The ID of the parent task',
		routing: { request: { url: '=/tasks/{{$value}}/taskassignments' } },
	},
	// ── Parent type + ID for createForParent/getForParent ────────────────────
	{
		displayName: 'Parent Resource',
		name: 'parentResource',
		type: 'options',
		required: true,
		displayOptions: { show: { resource: ['task'], operation: ['createForParent', 'getForParent'] } },
		options: taskParentOptions,
		default: 'projects',
		description: 'The type of parent resource the task is linked to',
	},
	{
		displayName: 'Parent ID',
		name: 'parentId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['task'], operation: ['createForParent', 'getForParent'] } },
		default: '',
		description: 'The ID of the parent resource',
		routing: { request: { url: '=/{{$parameter["parentResource"]}}/{{$value}}/tasks' } },
	},
	// ── Subtask required fields ──────────────────────────────────────────────
	{
		displayName: 'Subtask Title',
		name: 'subtaskTitle',
		type: 'string',
		displayOptions: { show: { resource: ['task'], operation: ['createSubtask'] } },
		default: '',
		routing: { request: { body: { title: '={{ $value }}' } } },
	},
	{
		displayName: 'Subtask Completed',
		name: 'subtaskCompleted',
		type: 'boolean',
		displayOptions: { show: { resource: ['task'], operation: ['createSubtask'] } },
		default: false,
		routing: { request: { body: { completed: '={{ $value }}' } } },
	},
	// ── Task Assignment required fields ──────────────────────────────────────
	{
		displayName: 'Assignee (Crew Path)',
		name: 'assigneeCrew',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['task'], operation: ['createTaskAssignment'] } },
		default: '',
		placeholder: '/crew/0',
		description: 'Resource path of the crew member to assign',
		routing: { request: { body: { crew: '={{ $value }}' } } },
	},
	// ── Color required field for create / createForParent ────────────────────
	{
		displayName: 'Color',
		name: 'color',
		type: 'color',
		required: true,
		displayOptions: { show: { resource: ['task'], operation: ['create', 'createForParent'] } },
		default: '#000000',
		description: 'Required: task color (any CSS-style hex code, e.g. #FF6600)',
		routing: { request: { body: { color: '={{ $value }}' } } },
	},
	// ── Pagination ───────────────────────────────────────────────────────────
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: {
			show: {
				resource: ['task'],
				operation: ['getAll', 'getForParent', 'getSubtasks', 'getTaskAssignments', 'getFiles', 'getFileFolders'],
			},
		},
		default: false,
		routing: {
			send: { paginate: true },
			operations: {
				pagination: {
					type: 'generic',
					properties: {
						continue: '={{ !!$response.body?.next_page_url && $parameter["returnAll"] }}',
						request: { url: '={{ $response.body?.next_page_url ?? $request.url }}' },
					},
				},
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		description: 'Max number of results to return',
		displayOptions: {
			show: {
				resource: ['task'],
				operation: ['getAll', 'getForParent', 'getSubtasks', 'getTaskAssignments', 'getFiles', 'getFileFolders'],
				returnAll: [false],
			},
		},
		typeOptions: { minValue: 1 },
		default: 50,
		routing: { request: { qs: { limit: '={{ $value }}' } } },
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['task'],
				operation: ['getAll', 'getForParent', 'getSubtasks', 'getTaskAssignments', 'getFiles', 'getFileFolders'],
				returnAll: [false],
			},
		},
		typeOptions: { minValue: 0 },
		default: 0,
		description: 'Number of results to skip for offset-based pagination',
		routing: { request: { qs: { offset: '={{ $value > 0 ? $value : undefined }}' } } },
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		displayOptions: {
			show: {
				resource: ['task'],
				operation: ['getAll', 'getForParent', 'getSubtasks', 'getTaskAssignments', 'getFiles', 'getFileFolders'],
			},
		},
		default: {},
		options: [
			{
				displayName: 'Created After',
				name: 'created_gt',
				type: 'dateTime',
				default: '',
				description: 'Return only records created after this date',
				routing: { request: { qs: { 'created[gt]': '={{ $value }}' } } },
			},
			{
				displayName: 'Fields',
				name: 'fields',
				type: 'string',
				default: '',
				placeholder: 'ID,displayname,modified',
				description: 'Comma-separated list of fields to return. Leave empty for all fields.',
				routing: { request: { qs: { fields: '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'ID Greater Than',
				name: 'id_gt',
				type: 'number',
				default: 0,
				description: 'Return only records with ID greater than this value. Useful for incremental sync.',
				routing: { request: { qs: { 'id[gt]': '={{ $value > 0 ? $value : undefined }}' } } },
			},
			{
				displayName: 'Modified After',
				name: 'modified_gt',
				type: 'dateTime',
				default: '',
				description: 'Return only records modified after this date',
				routing: { request: { qs: { 'modified[gt]': '={{ $value }}' } } },
			},
			{
				displayName: 'Modified Before',
				name: 'modified_lt',
				type: 'dateTime',
				default: '',
				description: 'Return only records modified before this date',
				routing: { request: { qs: { 'modified[lt]': '={{ $value }}' } } },
			},
			{
				displayName: 'Sort',
				name: 'sort',
				type: 'string',
				default: '+id',
				placeholder: '+ID or -modified',
				description: 'Sort field with direction prefix: + for ascending, - for descending',
				routing: { request: { qs: { sort: '={{ $value }}' } } },
			},
		],
	},
	customQueryParamsField('task'),
	// ── Body fields for create / createForParent / update ────────────────────
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { resource: ['task'], operation: ['create', 'createForParent', 'update'] } },
		default: {},
		options: taskBodyFields,
	},
];
