import type { INodeProperties } from 'n8n-workflow';
import { customQueryParamsField } from './shared';

const postReceive = [{ type: 'rootProperty' as const, properties: { property: 'data' } }];

export const vehicleOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['vehicle'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a vehicle',
				description: 'Create a new vehicle',
				routing: {
					request: { method: 'POST', url: '/vehicles' },
					output: { postReceive },
				},
			},
			{
				name: 'Create For Stock Location',
				value: 'createForStockLocation',
				action: 'Create a vehicle for a stock location',
				description: 'Create a vehicle linked to a specific stock location',
				routing: {
					request: { method: 'POST' },
					output: { postReceive },
				},
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a vehicle',
				description: 'Delete a vehicle by ID',
				routing: {
					request: { method: 'DELETE' },
					output: {
						postReceive: [
							{
								type: 'set',
								properties: { value: '={{ { "deleted": true } }}' },
							},
						],
					},
				},
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a vehicle',
				description: 'Get a single vehicle by ID',
				routing: { request: { method: 'GET' }, output: { postReceive } },
			},
			{
				name: 'Get Collection',
				value: 'getAll',
				action: 'Get collection of vehicles',
				description: 'Get a list of vehicles',
				routing: { request: { method: 'GET', url: '/vehicles' }, output: { postReceive } },
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a vehicle',
				description: 'Update an existing vehicle',
				routing: { request: { method: 'PUT' }, output: { postReceive } },
			},
		],
		default: 'getAll',
	},
];

const vehicleBodyFields: INodeProperties['options'] = [
	{
		displayName: 'Asset Location (Path)',
		name: 'asset_location',
		type: 'string',
		default: '',
		placeholder: '/stocklocations/0',
		description: 'Resource path of the asset stock location',
		routing: { request: { body: { asset_location: '={{ $value }}' } } },
	},
	{
		displayName: 'Cost Rate (Path)',
		name: 'cost_rate',
		type: 'string',
		default: '',
		placeholder: '/rates/0',
		description: 'Resource path of the cost rate',
		routing: { request: { body: { cost_rate: '={{ $value }}' } } },
	},
	{
		displayName: 'Folder (Path)',
		name: 'folder',
		type: 'string',
		default: '',
		placeholder: '/folders/0',
		routing: { request: { body: { folder: '={{ $value }}' } } },
	},
	{
		displayName: 'Height',
		name: 'height',
		type: 'number',
		default: 0,
		routing: { request: { body: { height: '={{ $value }}' } } },
	},
	{
		displayName: 'Image (Path)',
		name: 'image',
		type: 'string',
		default: '',
		placeholder: '/files/0',
		routing: { request: { body: { image: '={{ $value }}' } } },
	},
	{
		displayName: 'In Planner',
		name: 'in_planner',
		type: 'boolean',
		default: true,
		routing: { request: { body: { in_planner: '={{ $value }}' } } },
	},
	{
		displayName: 'Inspection Date',
		name: 'inspection_date',
		type: 'dateTime',
		default: '',
		routing: { request: { body: { inspection_date: '={{ $value }}' } } },
	},
	{
		displayName: 'Length',
		name: 'length',
		type: 'number',
		default: 0,
		routing: { request: { body: { length: '={{ $value }}' } } },
	},
	{
		displayName: 'License Plate',
		name: 'licenseplate',
		type: 'string',
		default: '',
		routing: { request: { body: { licenseplate: '={{ $value }}' } } },
	},
	{
		displayName: 'Multiple',
		name: 'multiple',
		type: 'boolean',
		default: false,
		description: 'Whether the vehicle can be scheduled more than once at the same time (for example, for employment agencies)',
		routing: { request: { body: { multiple: '={{ $value ? 1 : 0 }}' } } },
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		routing: { request: { body: { name: '={{ $value }}' } } },
	},
	{
		displayName: 'Payload Capacity',
		name: 'payload_capacity',
		type: 'number',
		default: 0,
		routing: { request: { body: { payload_capacity: '={{ $value }}' } } },
	},
	{
		displayName: 'Remark',
		name: 'remark',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		routing: { request: { body: { remark: '={{ $value }}' } } },
	},
	{
		displayName: 'Seats',
		name: 'seats',
		type: 'number',
		default: 0,
		typeOptions: { minValue: 0 },
		routing: { request: { body: { seats: '={{ $value }}' } } },
	},
	{
		displayName: 'Surface Area',
		name: 'surface_area',
		type: 'string',
		default: '',
		routing: { request: { body: { surface_area: '={{ $value }}' } } },
	},
	{
		displayName: 'Width',
		name: 'width',
		type: 'number',
		default: 0,
		routing: { request: { body: { width: '={{ $value }}' } } },
	},
];

export const vehicleFields: INodeProperties[] = [
	// ID for get/update/delete
	{
		displayName: 'Vehicle ID',
		name: 'vehicleId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['vehicle'], operation: ['get', 'update', 'delete'] } },
		default: '',
		description: 'The ID of the vehicle',
		routing: { request: { url: '=/vehicles/{{$value}}' } },
	},
	// Stock Location ID for createForStockLocation
	{
		displayName: 'Stock Location ID',
		name: 'stockLocationId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['vehicle'], operation: ['createForStockLocation'] } },
		default: '',
		description: 'The ID of the stock location to create the vehicle for',
		routing: { request: { url: '=/stocklocations/{{$value}}/vehicles' } },
	},
	// Pagination
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['vehicle'], operation: ['getAll'] } },
		default: false,
		routing: {
			send: { paginate: true },
			operations: {
				pagination: {
					type: 'generic',
					properties: {
						continue: '={{ !!$response.body?.next_page_url && $parameter["returnAll"] }}',
						request: { url: '={{ $response.body?.next_page_url ?? $request.url }}' },
					},
				},
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		description: 'Max number of results to return',
		displayOptions: { show: { resource: ['vehicle'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 1 },
		default: 50,
		routing: { request: { qs: { limit: '={{ $value }}' } } },
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		displayOptions: { show: { resource: ['vehicle'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 0 },
		default: 0,
		description: 'Number of results to skip for offset-based pagination',
		routing: { request: { qs: { offset: '={{ $value > 0 ? $value : undefined }}' } } },
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		displayOptions: { show: { resource: ['vehicle'], operation: ['getAll'] } },
		default: {},
		options: [
			{
				displayName: 'Created After',
				name: 'created_gt',
				type: 'dateTime',
				default: '',
				description: 'Return only records created after this date',
				routing: { request: { qs: { 'created[gt]': '={{ $value }}' } } },
			},
			{
				displayName: 'Fields',
				name: 'fields',
				type: 'string',
				default: '',
				placeholder: 'ID,displayname,modified',
				description: 'Comma-separated list of fields to return. Leave empty for all fields.',
				routing: { request: { qs: { fields: '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'ID Greater Than',
				name: 'id_gt',
				type: 'number',
				default: 0,
				description: 'Return only records with ID greater than this value. Useful for incremental sync.',
				routing: { request: { qs: { 'id[gt]': '={{ $value > 0 ? $value : undefined }}' } } },
			},
			{
				displayName: 'Modified After',
				name: 'modified_gt',
				type: 'dateTime',
				default: '',
				description: 'Return only records modified after this date',
				routing: { request: { qs: { 'modified[gt]': '={{ $value }}' } } },
			},
			{
				displayName: 'Modified Before',
				name: 'modified_lt',
				type: 'dateTime',
				default: '',
				description: 'Return only records modified before this date',
				routing: { request: { qs: { 'modified[lt]': '={{ $value }}' } } },
			},
			{
				displayName: 'Sort',
				name: 'sort',
				type: 'string',
				default: '+id',
				placeholder: '+ID or -modified',
				description: 'Sort field with direction prefix: + for ascending, - for descending',
				routing: { request: { qs: { sort: '={{ $value }}' } } },
			},
		],
	},
	customQueryParamsField('vehicle'),
	// Create body fields
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { resource: ['vehicle'], operation: ['create', 'createForStockLocation'] } },
		default: {},
		options: vehicleBodyFields,
	},
	// Update body fields
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show: { resource: ['vehicle'], operation: ['update'] } },
		default: {},
		options: vehicleBodyFields,
	},
];
